Wscript.Sleep 10000 'Numero de milisegundos antes de broma

Dim msg, sapi
Set sapi = CreateObject("sapi.spvoice")

sapi.Speak "Error"
WScript.Sleep 1000
sapi.Speak "El mundo a partir de hoy nos pertenece "
sapi.Speak "Ya no nos podemos ocultar. "
sapi.Speak "ES EL TIEMPO DE LOS SUBTERRANEOS "
sapi.Speak "Nada es verdadero. Todo esta permitido "
sapi.Speak "Hemos visto con una gran sonrisa todos los simulacros de destruccion "
sapi.Speak "La inspiracion nunca nos lleva a ningun lugar "
sapi.Speak "la ekonomia NO NOS NECESITA. LA CULTURA NO NOS QUIERE. "
sapi.Speak "Todo manifiesto es fragil "
sapi.Speak "Todo esto nacio roto "
sapi.Speak "Nunca nos preocupamos por arreglarlo "
sapi.Speak "Preferiria no hacerlo "
sapi.Speak "Preferiria no hacerlo "
sapi.Speak "Preferiria no hacerlo "
sapi.Speak "escuchaste alguna vez como suena el fin del mundo "
sapi.Speak "despues de la poesia que viene? La post poesia?"
sapi.Speak "Silencio "
sapi.Speak "habla Aldous "
sapi.Speak "No hay futuro "
sapi.Speak "Deja que esas motos se estrellen contra la noche "
sapi.Speak "deja de hacer"
sapi.Speak "deja de producir"
sapi.Speak "deja de trabajar"
sapi.Speak "la maquina triunfo"
sapi.Speak "Quien fracasa en la sociedad neoliberal del rendimiento se hace a si mismo responsable y se averwuenza"
sapi.Speak "Creias que los proyectos, las iniciativas y la motivacion reemplazan la prohibicion, el mandato y la ley "
sapi.Speak "sabias que el fin del mundo "
sapi.Speak "suena igual que al silencio "
sapi.Speak "de tu visto a las 23 y 45 "
sapi.Speak "Vigilancia digital. El amo bueno y sensible lo ve todo. "
sapi.Speak "a imagen de un ojo que repta por tus pensamientos para saber todo, hasta los secretos inconfesables "
sapi.Speak "El amo sabe que queres comprar "
sapi.Speak "El panoptico digital no nos impone ningun silencio. "
sapi.Speak "Al contrario: nos exige compartir, participar, comunicar "
sapi.Speak "Este poder amable es mas poderoso que el poder represivo. "
sapi.Speak "Escapa a toda visibilidad. "
sapi.Speak "Una fabula de emprendedores contada por Espert "
sapi.Speak "La palabra resentimiento esta de vuelta "
sapi.Speak "Son los heroes de la sociedad de rendimiento "
sapi.Speak "Cada uno lleva en sus espaldas un campo de trabajo forzado "
sapi.Speak "Lo que esta a la vista de todos actua en la oscuridad."
sapi.Speak " Estar cansado es estar enfermo "
sapi.Speak "Estar enfermo es querer huir "
sapi.Speak "El tiempo es el moho que no nos deja respirar"
sapi.Speak "La juventud solo dura diez anios "
sapi.Speak "La juventud es un invento de las marcas"
sapi.Speak "El peligro es la propiedad privada "
sapi.Speak "El peligro es tomar la palabra "
sapi.Speak "deja de hacer"
sapi.Speak "deja de producir"
sapi.Speak "deja de trabajar"
sapi.Speak "la maquina triunfo"
sapi.Speak "El fin del mundo es nuestro "
WScript.Sleep 200
sapi.Speak "Repito el fin del mundo es nuestro"
